Visiual(s)
masamonoke/randomniy-polutoksisch pull request #4
Opened 2022-06-02 13:34 UTC by GreatAngel01

Изменение отрисовки тайлов ,изменение спрайтов
изменение отрисовки поворота персонажа на поворот холста
добавлены спрайты и внедрена генерация Ильи

2022-06-08 12:35 UTC, masamonoke requested changes
1) Падает, если при числе тайлов > 70
2)По идее начальные значения в Visual Data, такие как размеры тайла, персонажа и размеры окна должны задаваться из конструктора

2022-06-08 15:47 UTC, GreatAngel01 commented
1) Я хз как править, ошибка та же что и обычно, на это выделенное количество памяти не влияет
2) Ок,можно доделать,но не критично
3) сделаю

2022-06-08 16:04 UTC, masamonoke commented
Просто переставь на 70 размер карты. Мне вообще больше интересно, чтобы ты сделал новый пр и посмотреть, что будет. По-идее он должен автоматически к текущему подцепиться

2022-06-21 13:30 UTC, GreatAngel01 commented
1)Изменён размер карты 200x200,работает прекрасно
2)Задаётся конструктором через App
3)В будущем

2022-06-21 14:34 UTC, masamonoke approved these changes

2022-06-21 14:35 UTC, merged